#name: Postagem Linkedin (INATIVO)
on:
  schedule: # Executar fluxo de trabalho
    - cron: '0 * * * *' # Executa a cada hora, na hora
  workflow_dispatch: # Executa o workflow manualmente (sem esperar que o cron seja chamado), através da página Github Actions Workflow diretamente
jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.linkedin.com/pulse/tratamento-de-dados-marcio-ferreira-junior/"
