name: tirinha charge

on:
    workflow_dispatch:
    schedule:
        # Funciona às 8h UTC todas as segundas, quartas e sextas-feiras
        - cron: "0 8 * * 1,3,5"

jobs:
    update-readme:
        name: Atualizar README com Comic Strip
        runs-on: ubuntu-latest
        steps:
            - uses: marciofjr/tirinhabr_readme@v1
              with:
                  SHOW_XKCD: true
